services:
  with-docker-multi-env-development:
    build:
      context: ../../
      dockerfile: docker/development/Dockerfile
    image: with-docker-multi-env-development
    ports:
      - "3001:3000"
  wevets-db:
    image: postgres:18   # A imagem que este serviço usará
    environment:
      - POSTGRES_PASSWORD=123